on: workflow_dispatch

jobs:
  jbang:
    runs-on: ubuntu-latest
    name: A job to run jbang
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: /root/.jbang
        key: $-jbang-$
        restore-keys: |
            $-jbang-
    - uses: graalvm/setup-graalvm@v1
      with:
        version: 'latest'
        java-version: '19'
        components: 'native-image'
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: print JAVA_HOME
      run: echo $JAVA_HOME
    - name: print GRAALVM_HOME
      run: ls $GRAALVM_HOME/bin
    - name: jbang
      uses: jbangdev/jbang-action@v0.106.1
      with:
        script: export native main.java
        scriptargs: ""
      env:
        JBANG_REPO: /root/.jbang/repository
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
