on: workflow_dispatch

jobs:
  jbang:
    runs-on: ubuntu-latest
    name: A job to run jbang
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: /root/.jbang
        key: $-jbang-$
        restore-keys: |
            $-jbang-
    - name: jbang
      uses: jbangdev/jbang-action@v0.106.1
      with:
        script: main.java
        scriptargs: ""
      env:
        JBANG_REPO: /root/.jbang/repository
        GITHUB_TOKEN: $
