on: workflow_dispatch

jobs:
  jbang:
    runs-on: ubuntu-latest
    name: A job to run jbang
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: /root/.jbang
        key: $-jbang-$
        restore-keys: |
            $-jbang-
    - uses: graalvm/setup-graalvm@v1
      with:
        version: 'latest'
        java-version: '19'
        components: 'native-image'
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: print JAVA_HOME
      run: echo $JAVA_HOME
    - name: install jbang
      run: curl -Ls https://sh.jbang.dev | bash -s - app setup
    - name: run app
      run: bash -c "jbang --verbose run --native main.java"
